CREATE ROLE admin LOGIN PASSWORD 'admin_pass';
CREATE ROLE app LOGIN PASSWORD 'app_pass';
CREATE ROLE readonly LOGIN PASSWORD 'readonly_pass';

GRANT CONNECT ON DATABASE flytics TO admin, app, readonly;
GRANT USAGE ON SCHEMA public TO admin, app, readonly;


ALTER ROLE admin CREATEDB;

GRANT ALL ON SCHEMA public TO admin;
GRANT ALL ON ALL TABLES IN SCHEMA public TO admin;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO admin;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO admin;


GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA public to app;

GRANT USAGE, SELECT
ON ALL SEQUENCES IN SCHEMA public TO app;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO app;


GRANT SELECT ON ALL TABLES IN SCHEMA public to readonly;

GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO readonly;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON SEQUENCES TO readonly;


