services:
  postgres:
    image: postgres:17
    container_name: flytics_db
    environment:
      POSTGRES_DB: flytics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "54322:5432"
    command: >
      postgres
      -c shared_preload_libraries=pg_stat_statements
      -c pg_stat_statements.track=all
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d flytics"]
      interval: 5s
      timeout: 5s
      retries: 5

  flyway:
    image: flyway/flyway
    container_name: flytics_flyway
    depends_on:
      postgres:
        condition: service_healthy
    command:
      - "migrate"
      - "-baselineOnMigrate=true"
    volumes:
      - ./db/migrations:/flyway/sql
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/flytics
      FLYWAY_USER: postgres
      FLYWAY_PASSWORD: postgres
      FLYWAY_BASELINE_VERSION: 1
      FLYWAY_BASELINE_DESCRIPTION: "Initial baseline"
      FLYWAY_SCHEMAS: public

  pgadmin:
    image: dpage/pgadmin4
    container_name: flytics_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: flytics_exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgres@postgres:5432/flytics?sslmode=disable"
    volumes:
      - ./queries.yaml:/queries.yaml
    command:
      - "--extend.query-path=/queries.yaml"
      - "--collector.stat_statements"
    ports:
      - "9187:9187"
    depends_on:
      postgres:
        condition: service_healthy

  prometheus:
    image: prom/prometheus
    container_name: flytics_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - postgres_exporter

  grafana:
    image: grafana/grafana
    container_name: flytics_grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  pg_data:

